spring.application.name=payment-procesor
# Kafka Server
spring.kafka.consumer.bootstrap-servers=localhost:9092

# Group ID (VERY IMPORTANT)
spring.kafka.consumer.group-id=processor-group

# Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Auto Offset
spring.kafka.consumer.auto-offset-reset=earliest

# Auto Commit
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-commit-interval=1000
spring.kafka.producer.acks=all
spring.kafka.producer.enable-idempotence=true
spring.kafka.consumer.max-poll-records=50

# Trusted package (for JSON)
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# Datasource
#spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=1234

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.generate-unique-name=false
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=/h2-console
server.port=8081