spring.application.name=payment-ingestor
server.port=8080

# Kafka Server
spring.kafka.producer.bootstrap-servers=localhost:9092

# Key & Value Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Reliability
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Performance
spring.kafka.producer.batch-size=16384
spring.kafka.producer.linger-ms=5
spring.kafka.producer.buffer-memory=33554432


